board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    #전체 게시판
    path('', views.board_list, name='board_list'),
    path('search/', views.board_search, name='board_search'),
    #일반인 페이지
    path('public/', views.board_public_list, name='board_public_list'),
    path('public/write/<int:pk>', views.board_public_write, name='board_public_write'),
    path('public/detail/<int:pk>/', views.board_public_detail, name='board_public_detail'),
    path('public/download/', views.file_download, name='file_download'),
    path('public/detail/<int:pk>/delete/', views.board_public_delete, name='board_public_delete'),
    path('public/detail/<int:pk>/modify/', views.board_public_modify, name='board_public_modify'),
    path('public/search/', views.board_public_search, name='board_public_search'),
    #좋아요
    path('<int:pk>/likes/', views.likes, name='likes'),
    #댓글
    path('public/detail/<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),

    #과학자 페이지
    path('science/', views.board_science_list, name='board_science_list'),
    path('science/write/<int:pk>', views.board_science_write, name='board_science_write'),
    path('science/detail/<int:pk>/', views.board_science_detail, name='board_science_detail'),
    path('science/download/', views.file_download, name='file_download'),
    path('science/detail/<int:pk>/delete/', views.board_science_delete, name='board_science_delete'),
    path('science/detail/<int:pk>/modify/', views.board_science_modify, name='board_science_modify'),
    path('science/search/', views.board_science_search, name='board_science_search'),
    #좋아요
    path('science/<int:pk>/likes/', views.board_science_likes, name='board_science_likes'),
]

igweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.views.generic import RedirectView
# Summernote 설정
from django.conf import settings
from django.conf.urls.static import static
from igwebapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('rword.urls')),
]

urlpatterns += [path('summernote/', include('django_summernote.urls'))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/forms.py
from tkinter import Widget
from django import forms
from .models import Board, Comment
from django_summernote.fields import SummernoteTextField
from django_summernote.widgets import SummernoteWidget
from django.forms import TextInput

#일반인
class PBoardWriteForm(forms.ModelForm):
    title = forms.CharField(
        label='글 제목',
        widget=forms.TextInput(
            attrs={
                'class': "form-control",
                'placeholder': '게시글 제목'
            }
        ),
        required=True,
    )

    contents = SummernoteTextField()

    field_order = [
        'title',
        #'writer',
        #'sentence',
        'image',
        'contents',
        'file',

    ]

    class Meta:
        model = Board
        fields = [
            'title',
            'contents',
            #'sentence',
            #'writer',
            'image',
            'file'
        ]
        widgets = {
            'contents' : SummernoteWidget()
        }
    
    def clean(self):
        cleaned_data = super().clean()

        title = cleaned_data.get('title', '')
        contents = cleaned_data.get('contents', '')
        # writer = cleaned_data.get('writer', '')
        #sentence = cleaned_data.get('sentence', '')
        image = cleaned_data.get('image', '')
        file = cleaned_data.get('file', '')

        if title == '':
            self.add_error('title', '글 제목을 입력하세요.')
        elif image == '':
            self.add_error('image', '썸네일 이미지를 등록하세요.')
        elif contents == '':
            self.add_error('contents', '글 내용을 입력하세요.')
        else:
            self.title = title
            self.contents = contents
            #self.writer = writer
            #self.sentence = sentence
            self.image = image
            self.file = file



#과학자
class SBoardWriteForm(forms.ModelForm):
    title = forms.CharField(
        label='글 제목',
        widget=forms.TextInput(
            attrs={
                'class': "form-control",
                'placeholder': '게시글 제목'
            }
        ),
        required=True,
    )
    # sentence = forms.CharField(
    #     label='문장',
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': "form-control",
    #             'placeholder': '문장'
    #         }
    #     ),
    #     required=True,
    # )

    contents = SummernoteTextField()

    field_order = [
        'title',
        #'writer',
        #'sentence',
        'contents',
        'file',
    ]

    class Meta:
        model = Board
        fields = [
            'title',
            'contents',
            #'sentence',
            #'writer',
            'file'
        ]
        widgets = {
            'contents' : SummernoteWidget()
        }
    
    def clean(self):
        cleaned_data = super().clean()

        title = cleaned_data.get('title', '')
        contents = cleaned_data.get('contents', '')
        #writer = cleaned_data.get('writer', '')
        #sentence = cleaned_data.get('sentence', '')
        file = cleaned_data.get('file', '')

        if title == '':
            self.add_error('title', '글 제목을 입력하세요.')
        elif contents == '':
            self.add_error('contents', '글 내용을 입력하세요.')
        else:
            self.title = title
            self.contents = contents
            #self.writer = writer
            #self.sentence = sentence
            self.file = file

#댓글
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('board', 'user',)
        widgets = {
            'content': TextInput(attrs={
                'class': "text-add",
                'placeholder': '내 의견 달기..',
                #'style' : ''
                }),
    }

board/views.py
import os
import re
from urllib import response
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PBoardWriteForm, SBoardWriteForm, CommentForm
from .models import Board, BoardLikeUsers, Comment
from django.core.paginator import Paginator
from django.conf import settings
from django.http import HttpResponse
from django.db.models import Q
from django.db.models import Count
from django.contrib import messages 
from rword.models import SentenceList

#### 전체 게시판 ####
def board_list(request):
    pb_boards = Board.objects.filter(board_name='Public').order_by('-id')
    sc_boards = Board.objects.filter(board_name='Science').order_by('-id')

    pb_paginator = Paginator(pb_boards, 10)
    pagenum = request.GET.get('page')
    pb_boards = pb_paginator.get_page(pagenum)

    sc_paginator = Paginator(sc_boards, 10)
    pagenum = request.GET.get('page')
    sc_boards = sc_paginator.get_page(pagenum)

    context = {
        'pb_boards' : pb_boards,
        'sc_boards' : sc_boards,
    }

    return render(request, 'board/board_list.html', context)

#파일 다운로드
def file_download(request):
    path = request.GET['path']
    file_path = os.path.join(settings.MEDIA_ROOT, path)

    binary_file = open(file_path, 'rb')
    response = HttpResponse(binary_file.read(), content_type="application/octet-stream; charset=utf-8")
    response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
    return response

# 검색
def board_search(request):
    pb_boards = Board.objects.filter(board_name='Public').order_by('-id')
    sc_boards = Board.objects.filter(board_name='Science').order_by('-id')

    q = request.GET.get('q', "")
    search_type = request.GET.get('type', "")

    if q:
        if search_type == "all":
            pb_boards = pb_boards.filter(Q (title__icontains=q)| Q (contents__icontains=q)| Q (writer__username__icontains=q)| Q (sentence__sentence__icontains=q))
            sc_boards = sc_boards.filter(Q (title__icontains=q)| Q (contents__icontains=q)| Q (writer__username__icontains=q)| Q (sentence__sentence__icontains=q))
        elif search_type == "title_contents":
            pb_boards = pb_boards.filter(Q (title__icontains=q)| Q (contents__icontains=q))
            sc_boards = sc_boards.filter(Q (title__icontains=q)| Q (contents__icontains=q))
        elif search_type == "title":
            pb_boards = pb_boards.filter(title__icontains=q)
            sc_boards = sc_boards.filter(title__icontains=q)
        elif search_type == "contents":
            pb_boards = pb_boards.filter(contents__icontains=q)
            sc_boards = sc_boards.filter(contents__icontains=q)
        elif search_type == "writer":
            pb_boards = pb_boards.filter(writer__username__icontains=q)
            sc_boards = sc_boards.filter(writer__username__icontains=q)
        elif search_type == "sentence":
            pb_boards = pb_boards.filter(sentence__sentence__icontains=q)
            sc_boards = sc_boards.filter(sentence__sentence__icontains=q)
        return render(request, 'board/board_search.html', {'pb_boards' : pb_boards,'sc_boards' : sc_boards, 'q' : q})
    
    else:
        return render(request, 'board/board_search.html')

#### 일반인 ####
#게시판 목록
def board_public_list(request):
    sort = request.GET.get('sort','')

    if sort == 'likes':
        pb_boards = Board.objects.filter(board_name='Public').annotate(like_count=Count('like_users')).order_by('-like_count', '-write_dttm')
    elif sort == 'hits':
        pb_boards = Board.objects.filter(board_name='Public').order_by('-hits', '-write_dttm')
    else:
        pb_boards = Board.objects.filter(board_name='Public').order_by('-id')

    paginator = Paginator(pb_boards, 10)
    pagenum = request.GET.get('page')
    pb_boards = paginator.get_page(pagenum)

    context = {
        'pb_boards' : pb_boards,
        'sort':sort,
    }

    return render(request, 'board_public/board_public_list.html', context)

#글 작성하기
def board_public_write(request, pk):
    if request.method == 'GET':
        sentenceObj = get_object_or_404(SentenceList, id=pk)
        write_form = PBoardWriteForm()
        context = {
            'forms': write_form,
        }
        return render(request, 'board_public/board_public_write.html', context)

    elif request.method == 'POST':
        sentenceObj = get_object_or_404(SentenceList, id=pk)
        write_form = PBoardWriteForm(request.POST, request.FILES)

        if write_form.is_valid():
            board = Board(
                title=write_form.title,
                contents=write_form.contents,
                writer=request.user,
                sentence=sentenceObj,
                image=write_form.image,
                #file=write_form.file
            )
            board.save()
            return redirect('/board/public')
        else:
            context = {
                'forms': write_form,
            }
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
            return render(request, 'board_public/board_public_write.html', context)

#글 상세보기
def board_public_detail(request, pk):
    board = get_object_or_404(Board, id=pk)
    comments = Comment.objects.filter(board=board.id).order_by('created_at')
    # 좋아요 수 띄우기
    like = BoardLikeUsers.objects.filter(board = board.id).annotate(Count('user'))
    like_num = like.count()
    #댓글
    comment_form = CommentForm()
    #조회수 (쿠키 이용)
    cookie_name = 'hit'

    context = {
        'board': board,
        'like_num' : like_num,
        'comment_form' : comment_form,
        'comments' : comments
    }

    response = render(request, 'board_public/board_public_detail.html', context)

    if request.COOKIES.get(cookie_name) is not None:
        cookies = request.COOKIES.get(cookie_name)
        cookies_list = cookies.split('|')
        if str(pk) not in cookies_list:
            response.set_cookie(cookie_name, cookies + f'|{pk}', expires=None)
            board.hits += 1
            board.save()
            return response
    else:
        response.set_cookie(cookie_name, pk, expires=None)
        board.hits += 1
        board.save()
        return response

    return render(request, 'board_public/board_public_detail.html', context)

#삭제하기 - user 설정 후 추가 설정 필요
def board_public_delete(request, pk):
    board = get_object_or_404(Board, id=pk)

    board.delete()
    return redirect('/board/public')

#수정하기 - user 설정 후 추가 설정 필요
def board_public_modify(request, pk):
    board = get_object_or_404(Board, id=pk)
    
    context = {
        'board': board,
    }

    if request.method == 'GET' or request.method == 'FILES':
        write_form = PBoardWriteForm(instance=board)
        context['forms'] = write_form
        return render(request, 'board_public/board_public_modify.html', context)
    
    elif request.method == 'POST':
        file_check = request.POST.get('file-clear', False)
        image_check = request.POST.get('image-clear', False)

        if file_check:
            os.remove(os.path.join(settings.MEDIA_ROOT, board.file.path))
            board.file = ''
        if image_check:
            if board.image == 'Images/favicon.png':
                board.image = 'Images/favicon.png'
            else:
                os.remove(os.path.join(settings.MEDIA_ROOT, board.image.path))
                board.image = 'Images/favicon.png'

        write_form = PBoardWriteForm(request.POST, request.FILES)

        if write_form.is_valid():
            board.title=write_form.title
            board.contents=write_form.contents
            if write_form.image:
                if board.image:
                    if board.image == 'Images/favicon.png':
                        pass
                    else:
                        os.remove(os.path.join(settings.MEDIA_ROOT, board.image.path))
                board.image=write_form.image
            if write_form.file:
                if board.file:
                    os.remove(os.path.join(settings.MEDIA_ROOT, board.file.path))
                board.file=write_form.file
            
            board.save()
            return redirect('/board/public')
        else:
            context['forms'] = write_form
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
            return render(request, 'board_public/board_public_modify.html', context)

# 검색
def board_public_search(request):
    sort = request.GET.get('sort','')

    if sort == 'likes':
        boards = Board.objects.filter(board_name='Public').annotate(like_count=Count('like_users')).order_by('-like_count', '-write_dttm')
    elif sort == 'hits':
        boards = Board.objects.filter(board_name='Public').order_by('-hits', '-write_dttm')
    else:
        boards = Board.objects.filter(board_name='Public').order_by('-id')

    q = request.GET.get('q', '')
    search_type = request.GET.get('type', '')

    if q:
        if search_type == "all":
            boards = boards.filter(Q (title__icontains=q)| Q (contents__icontains=q)| Q (writer__username__icontains=q)| Q (sentence__sentence__icontains=q))
        elif search_type == "title_contents":
            boards = boards.filter(Q (title__icontains=q)| Q (contents__icontains=q))
        elif search_type == "title":
            boards = boards.filter(title__icontains=q)
        elif search_type == "contents":
            boards = boards.filter(contents__icontains=q)
        elif search_type == "writer":
            boards = boards.filter(writer__username__icontains=q)
        elif search_type == "sentence":
            boards = boards.filter(sentence__sentence__icontains=q)
        paginator = Paginator(boards, 10)
        pagenum = request.GET.get('page')
        boards = paginator.get_page(pagenum)

        context = {
            'boards' : boards,
            'q' : q,
            'type' : search_type,

board/templates/board/board_list.html
{% block contents %}
<div>게시판</div>
<div>검색</div>
<form action="{% url 'board:board_search' %}" method="GET"> 
    {% csrf_token %}
    <div style="overflow: hidden;">
        <div style="margin-top: 2px; float: left; padding-left: 10px;">
            <select style="width: 6em;" name="type">
                <option value="all">전체</option>
                <option value="title_contents">제목+내용</option>
                <option value="title">제목</option>
                <option value="contents">내용</option>
                <option value="writer">작성자</option>
                <option value="sentence">문장</option>
            </select>
        </div>
        <div style="float: left; padding-left: 10px;">
            <input type="search" placeholder="Search" aria-label="Search" name="q" value="{{q}}">
        </div>
        <div style="float: left; padding-left: 10px;">
            <button input type="submit">Search</button>
        </div>
    </div>
</form>
<div style="border: 1px black solid; margin: 20px 0px;"></div>

<div class="board">
    <div class="pb-board">
        <p>일반인 게시판</p>
        <div>
            {% if user.is_authenticated %}
            <a href="{% url 'board:board_public_write' %}"><button>글쓰기</button></a>
            {% endif %}
            <a href="{% url 'board:board_public_list' %}"><button>게시판 이동</button></a>
        </div>
        <br>
        {% if not pb_boards%}
        <p>작성된 게시글이 없습니다.</p>
        {% else %}
        <table style="text-align:center; border:1px solid black;">
            <thead>
                <tr class="header">
                    <th scope="col">제목</th>
                    <th scope="col">작성자</th>
                    <th scope="col">글 작성일</th>
                </tr>
            </thead>
    
            <tbody>
                {% for board in pb_boards %}
                {% if board %}
                <tr>
                    <th scope="row">{{ board.title }}</th>
                    <td>{{ board.writer }}</td>
                    <td>{{ board.write_dttm }}</td>
                    <td><a href="/board/public/detail/{{ board.id }}" target="_self"><button>상세보기</button></a></td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
    <div class="sc-board">
        <p>과학자 게시판</p>
        <div>
            {% if user.is_authenticated %}
            <a href="{% url 'board:board_science_write' %}"><button>글쓰기</button></a>
            {% endif %}
            <a href="{% url 'board:board_science_list' %}"><button>게시판 이동</button></a>
        </div>
        <br>
        {% if not sc_boards%}
        <p>작성된 게시글이 없습니다.</p>
        {% else %}
        <table style="text-align:center; border:1px solid black;">
            <thead>
                <tr class="header">
                    <th scope="col">제목</th>
                    <th scope="col">작성자</th>
                    <th scope="col">글 작성일</th>
                </tr>
            </thead>
    
            <tbody>
                {% for board in sc_boards %}
                {% if board %}
                <tr>
                    <th scope="row">{{ board.title }}</th>
                    <td>{{ board.writer }}</td>
                    <td>{{ board.write_dttm }}</td>
                    <td><a href="/board/science/detail/{{ board.id }}" target="_self"><button>상세보기</button></a></td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>

<style>
    .board {
        display: flex;
    }

    .pb-board {
        width: 50%;
        padding-left: 25px;
    }

    .sc-board {
        width: 50%;
        border-left: 2px black double;
        padding-left: 25px;
    }
</style>
{% endblock contents %}

board/templates/board/board_modify.html
{% block contents %}
<div>게시판 수정하기</div>
<form action="" method="POST">
    {% csrf_token %}

    {% for form in forms %}
    <div>
        <label for="{{ form.id_for_label }}">{{ form.label }}</label>
        {{ form }}
    </div>
    {% endfor %} 

    {% if error %} 
    {{ error }}
    {% endif %}
    <button type="submit">글 수정하기</button>
</form>
{% endblock contents %}

board/templates/board/board_search.html
<div>검색</div>
<a href="{% url 'board:board_list' %}"><button>전체 게시판으로 돌아가기</button></a>
<form action="{% url 'board:board_search' %}" method="GET"> 
    {% csrf_token %}
    <div style="overflow: hidden;">
        <div style="margin-top: 2px; float: left; padding-left: 10px;">
            <select style="width: 6em;" name="type">
                <option value="all">전체</option>
                <option value="title_contents">제목+내용</option>
                <option value="title">제목</option>
                <option value="contents">내용</option>
                <option value="writer">작성자</option>
                <option value="sentence">문장</option>
            </select>
        </div>
        <div style="float: left; padding-left: 10px;">
            <input type="search" placeholder="Search" aria-label="Search" name="q" value="{{q}}">
        </div>
        <div style="float: left; padding-left: 10px;">
            <button input type="submit">Search</button>
        </div>
    </div>
</form>    

    <div style="border: 1px black solid; margin: 20px 0px;"></div>

    <div class="board">
        <div class="pb-board">
            <p>일반인 게시판</p>
            <div>
                <a href="{% url 'board:board_public_write' %}"><button>글쓰기</button></a>
                <a href="{% url 'board:board_public_list' %}"><button>게시판 이동</button></a>
            </div>
            <br>
            {% if not pb_boards%}
            <p>검색 결과가 없습니다.</p>
            {% else %}
            <table style="text-align:center; border:1px solid black;">
                <thead>
                    <tr class="header">
                        <th scope="col">제목</th>
                        <th scope="col">작성자</th>
                        <th scope="col">글 작성일</th>
                    </tr>
                </thead>
        
                <tbody>
                    {% for board in pb_boards %}
                    {% if board %}
                    <tr>
                        <th scope="row">{{ board.title }}</th>
                        <td>{{ board.writer }}</td>
                        <td>{{ board.write_dttm }}</td>
                        <td><a href="/board/public/detail/{{ board.id }}" target="_self"><button>상세보기</button></a></td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
        <div class="sc-board">
            <p>과학자 게시판</p>
            <div>
                <a href="{% url 'board:board_science_write' %}"><button>글쓰기</button></a>
                <a href="{% url 'board:board_science_list' %}"><button>게시판 이동</button></a>
            </div>
            <br>
            {% if not sc_boards%}
            <p>검색 결과가 없습니다.</p>
            {% else %}
            <table style="text-align:center; border:1px solid black;">
                <thead>
                    <tr class="header">
                        <th scope="col">제목</th>
                        <th scope="col">작성자</th>
                        <th scope="col">글 작성일</th>
                    </tr>
                </thead>
        
                <tbody>
                    {% for board in sc_boards %}
                    {% if board %}
                    <tr>
                        <th scope="row">{{ board.title }}</th>
                        <td>{{ board.writer }}</td>
                        <td>{{ board.write_dttm }}</td>
                        <td><a href="/board/science/detail/{{ board.id }}" target="_self"><button>상세보기</button></a></td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>

    <style>
        .board {
            display: flex;
        }

        .pb-board {
            width: 50%;
            padding-left: 25px;
        }

        .sc-board {
            width: 50%;
            border-left: 2px black double;
            padding-left: 25px;
        }
    </style>

board/templates/board/board_write.html
{% block contents %}
<div>게시판 글쓰기</div>
<form action="" method="POST">
    {% csrf_token %}

    {% for form in forms %}
    <div>
        <label for="{{ form.id_for_label }}">{{ form.label }}</label>
        {{ form }}
    </div>
    {% endfor %} 

    {% if error %} 
    {{ error }}
    {% endif %}
    <button type="submit">저장하기</button>
</form>
{% endblock contents %}