board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    #전체 게시판
    path('', views.board_list, name='board_list'),
    path('search/', views.board_search, name='board_search'),
    #일반인 페이지
    path('public/', views.board_public_list, name='board_public_list'),
    path('public/write/<int:pk>', views.board_public_write, name='board_public_write'),
    path('public/detail/<int:pk>/', views.board_public_detail, name='board_public_detail'),
    path('public/download/', views.file_download, name='file_download'),
    path('public/detail/<int:pk>/delete/', views.board_public_delete, name='board_public_delete'),
    path('public/detail/<int:pk>/modify/', views.board_public_modify, name='board_public_modify'),
    path('public/search/', views.board_public_search, name='board_public_search'),
    #좋아요
    path('<int:pk>/likes/', views.likes, name='likes'),
    #댓글
    path('public/detail/<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),

    #과학자 페이지
    path('science/', views.board_science_list, name='board_science_list'),
    path('science/write/<int:pk>', views.board_science_write, name='board_science_write'),
    path('science/detail/<int:pk>/', views.board_science_detail, name='board_science_detail'),
    path('science/download/', views.file_download, name='file_download'),
    path('science/detail/<int:pk>/delete/', views.board_science_delete, name='board_science_delete'),
    path('science/detail/<int:pk>/modify/', views.board_science_modify, name='board_science_modify'),
    path('science/search/', views.board_science_search, name='board_science_search'),
    #좋아요
    path('science/<int:pk>/likes/', views.board_science_likes, name='board_science_likes'),
]

igweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.views.generic import RedirectView
# Summernote 설정
from django.conf import settings
from django.conf.urls.static import static
from igwebapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('rword.urls')),
]

urlpatterns += [path('summernote/', include('django_summernote.urls'))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/forms.py
from tkinter import Widget
from django import forms
from .models import Board, Comment
from django_summernote.fields import SummernoteTextField
from django_summernote.widgets import SummernoteWidget
from django.forms import TextInput

#일반인
class PBoardWriteForm(forms.ModelForm):
    title = forms.CharField(
        label='글 제목',
        widget=forms.TextInput(
            attrs={
                'class': "form-control",
                'placeholder': '게시글 제목'
            }
        ),
        required=True,
    )

    contents = SummernoteTextField()

    field_order = [
        'title',
        #'writer',
        #'sentence',
        'image',
        'contents',
        'file',

    ]

    class Meta:
        model = Board
        fields = [
            'title',
            'contents',
            #'sentence',
            #'writer',
            'image',
            'file'
        ]
        widgets = {
            'contents' : SummernoteWidget()
        }
    
    def clean(self):
        cleaned_data = super().clean()

        title = cleaned_data.get('title', '')
        contents = cleaned_data.get('contents', '')
        # writer = cleaned_data.get('writer', '')
        #sentence = cleaned_data.get('sentence', '')
        image = cleaned_data.get('image', '')
        file = cleaned_data.get('file', '')

        if title == '':
            self.add_error('title', '글 제목을 입력하세요.')
        elif image == '':
            self.add_error('image', '썸네일 이미지를 등록하세요.')
        elif contents == '':
            self.add_error('contents', '글 내용을 입력하세요.')
        else:
            self.title = title
            self.contents = contents
            #self.writer = writer
            #self.sentence = sentence
            self.image = image
            self.file = file



#과학자
class SBoardWriteForm(forms.ModelForm):
    title = forms.CharField(
        label='글 제목',
        widget=forms.TextInput(
            attrs={
                'class': "form-control",
                'placeholder': '게시글 제목'
            }
        ),
        required=True,
    )
    # sentence = forms.CharField(
    #     label='문장',
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': "form-control",
    #             'placeholder': '문장'
    #         }
    #     ),
    #     required=True,
    # )

    contents = SummernoteTextField()

    field_order = [
        'title',
        #'writer',
        #'sentence',
        'contents',
        'file',
    ]

    class Meta:
        model = Board
        fields = [
            'title',
            'contents',
            #'sentence',
            #'writer',
            'file'
        ]
        widgets = {
            'contents' : SummernoteWidget()
        }
    
    def clean(self):
        cleaned_data = super().clean()

        title = cleaned_data.get('title', '')
        contents = cleaned_data.get('contents', '')
        #writer = cleaned_data.get('writer', '')
        #sentence = cleaned_data.get('sentence', '')
        file = cleaned_data.get('file', '')

        if title == '':
            self.add_error('title', '글 제목을 입력하세요.')
        elif contents == '':
            self.add_error('contents', '글 내용을 입력하세요.')
        else:
            self.title = title
            self.contents = contents
            #self.writer = writer
            #self.sentence = sentence
            self.file = file

#댓글
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('board', 'user',)
        widgets = {
            'content': TextInput(attrs={
                'class': "text-add",
                'placeholder': '내 의견 달기..',
                #'style' : ''
                }),
    }

board/views.py
import os
import re
from urllib import response
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PBoardWriteForm, SBoardWriteForm, CommentForm
from .models import Board, BoardLikeUsers, Comment
from django.core.paginator import Paginator
from django.conf import settings
from django.http import HttpResponse
from django.db.models import Q
from django.db.models import Count
from django.contrib import messages 
from rword.models import SentenceList

#### 전체 게시판 ####
def board_list(request):
    pb_boards = Board.objects.filter(board_name='Public').order_by('-id')
    sc_boards = Board.objects.filter(board_name='Science').order_by('-id')

    pb_paginator = Paginator(pb_boards, 10)
    pagenum = request.GET.get('page')
    pb_boards = pb_paginator.get_page(pagenum)

    sc_paginator = Paginator(sc_boards, 10)
    pagenum = request.GET.get('page')
    sc_boards = sc_paginator.get_page(pagenum)

    context = {
        'pb_boards' : pb_boards,
        'sc_boards' : sc_boards,
    }

    return render(request, 'board/board_list.html', context)

#파일 다운로드
def file_download(request):
    path = request.GET['path']
    file_path = os.path.join(settings.MEDIA_ROOT, path)

    binary_file = open(file_path, 'rb')
    response = HttpResponse(binary_file.read(), content_type="application/octet-stream; charset=utf-8")
    response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
    return response

# 검색
def board_search(request):
    pb_boards = Board.objects.filter(board_name='Public').order_by('-id')
    sc_boards = Board.objects.filter(board_name='Science').order_by('-id')

    q = request.GET.get('q', "")
    search_type = request.GET.get('type', "")

    if q:
        if search_type == "all":
            pb_boards = pb_boards.filter(Q (title__icontains=q)| Q (contents__icontains=q)| Q (writer__username__icontains=q)| Q (sentence__sentence__icontains=q))
            sc_boards = sc_boards.filter(Q (title__icontains=q)| Q (contents__icontains=q)| Q (writer__username__icontains=q)| Q (sentence__sentence__icontains=q))
        elif search_type == "title_contents":
            pb_boards = pb_boards.filter(Q (title__icontains=q)| Q (contents__icontains=q))
            sc_boards = sc_boards.filter(Q (title__icontains=q)| Q (contents__icontains=q))
        elif search_type == "title":
            pb_boards = pb_boards.filter(title__icontains=q)
            sc_boards = sc_boards.filter(title__icontains=q)
        elif search_type == "contents":
            pb_boards = pb_boards.filter(contents__icontains=q)
            sc_boards = sc_boards.filter(contents__icontains=q)
        elif search_type == "writer":
            pb_boards = pb_boards.filter(writer__username__icontains=q)
            sc_boards = sc_boards.filter(writer__username__icontains=q)
        elif search_type == "sentence":
            pb_boards = pb_boards.filter(sentence__sentence__icontains=q)
            sc_boards = sc_boards.filter(sentence__sentence__icontains=q)
        return render(request, 'board/board_search.html', {'pb_boards' : pb_boards,'sc_boards' : sc_boards, 'q' : q})
    
    else:
        return render(request, 'board/board_search.html')

#### 일반인 ####
#게시판 목록
def board_public_list(request):
    sort = request.GET.get('sort','')

    if sort == 'likes':
        pb_boards = Board.objects.filter(board_name='Public').annotate(like_count=Count('like_users')).order_by('-like_count', '-write_dttm')
    elif sort == 'hits':
        pb_boards = Board.objects.filter(board_name='Public').order_by('-hits', '-write_dttm')
    else:
        pb_boards = Board.objects.filter(board_name='Public').order_by('-id')

    paginator = Paginator(pb_boards, 10)
    pagenum = request.GET.get('page')
    pb_boards = paginator.get_page(pagenum)

    context = {
        'pb_boards' : pb_boards,
        'sort':sort,
    }

    return render(request, 'board_public/board_public_list.html', context)

#글 작성하기
def board_public_write(request, pk):
    if request.method == 'GET':
        sentenceObj = get_object_or_404(SentenceList, id=pk)
        write_form = PBoardWriteForm()
        context = {
            'forms': write_form,
        }
        return render(request, 'board_public/board_public_write.html', context)

    elif request.method == 'POST':
        sentenceObj = get_object_or_404(SentenceList, id=pk)
        write_form = PBoardWriteForm(request.POST, request.FILES)

        if write_form.is_valid():
            board = Board(
                title=write_form.title,
                contents=write_form.contents,
                writer=request.user,
                sentence=sentenceObj,
                image=write_form.image,
                #file=write_form.file
            )
            board.save()
            return redirect('/board/public')
        else:
            context = {
                'forms': write_form,
            }
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
            return render(request, 'board_public/board_public_write.html', context)

#글 상세보기
def board_public_detail(request, pk):
    board = get_object_or_404(Board, id=pk)
    comments = Comment.objects.filter(board=board.id).order_by('created_at')
    # 좋아요 수 띄우기
    like = BoardLikeUsers.objects.filter(board = board.id).annotate(Count('user'))
    like_num = like.count()
    #댓글
    comment_form = CommentForm()
    #조회수 (쿠키 이용)
    cookie_name = 'hit'

    context = {
        'board': board,
        'like_num' : like_num,
        'comment_form' : comment_form,
        'comments' : comments
    }

    response = render(request, 'board_public/board_public_detail.html', context)

    if request.COOKIES.get(cookie_name) is not None:
        cookies = request.COOKIES.get(cookie_name)
        cookies_list = cookies.split('|')
        if str(pk) not in cookies_list:
            response.set_cookie(cookie_name, cookies + f'|{pk}', expires=None)
            board.hits += 1
            board.save()
            return response
    else:
        response.set_cookie(cookie_name, pk, expires=None)
        board.hits += 1
        board.save()
        return response

    return render(request, 'board_public/board_public_detail.html', context)

#삭제하기 - user 설정 후 추가 설정 필요
def board_public_delete(request, pk):
    board = get_object_or_404(Board, id=pk)

    board.delete()
    return redirect('/board/public')

#수정하기 - user 설정 후 추가 설정 필요
def board_public_modify(request, pk):
    board = get_object_or_404(Board, id=pk)
    
    context = {
        'board': board,
    }

    if request.method == 'GET' or request.method == 'FILES':
        write_form = PBoardWriteForm(instance=board)
        context['forms'] = write_form
        return render(request, 'board_public/board_public_modify.html', context)
    
    elif request.method == 'POST':
        file_check = request.POST.get('file-clear', False)
        image_check = request.POST.get('image-clear', False)

        if file_check:
            os.remove(os.path.join(settings.MEDIA_ROOT, board.file.path))
            board.file = ''
        if image_check:
            if board.image == 'Images/favicon.png':
                board.image = 'Images/favicon.png'
            else:
                os.remove(os.path.join(settings.MEDIA_ROOT, board.image.path))
                board.image = 'Images/favicon.png'

        write_form = PBoardWriteForm(request.POST, request.FILES)

        if write_form.is_valid():
            board.title=write_form.title
            board.contents=write_form.contents
            if write_form.image:
                if board.image:
                    if board.image == 'Images/favicon.png':
                        pass
                    else:
                        os.remove(os.path.join(settings.MEDIA_ROOT, board.image.path))
                board.image=write_form.image
            if write_form.file:
                if board.file:
                    os.remove(os.path.join(settings.MEDIA_ROOT, board.file.path))
                board.file=write_form.file
            
            board.save()
            return redirect('/board/public')
        else:
            context['forms'] = write_form
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
            return render(request, 'board_public/board_public_modify.html', context)

# 검색
def board_public_search(request):
    sort = request.GET.get('sort','')

    if sort == 'likes':
        boards = Board.objects.filter(board_name='Public').annotate(like_count=Count('like_users')).order_by('-like_count', '-write_dttm')
    elif sort == 'hits':
        boards = Board.objects.filter(board_name='Public').order_by('-hits', '-write_dttm')
    else:
        boards = Board.objects.filter(board_name='Public').order_by('-id')

    q = request.GET.get('q', '')
    search_type = request.GET.get('type', '')

    if q:
        if search_type == "all":
            boards = boards.filter(Q (title__icontains=q)| Q (contents__icontains=q)| Q (writer__username__icontains=q)| Q (sentence__sentence__icontains=q))
        elif search_type == "title_contents":
            boards = boards.filter(Q (title__icontains=q)| Q (contents__icontains=q))
        elif search_type == "title":
            boards = boards.filter(title__icontains=q)
        elif search_type == "contents":
            boards = boards.filter(contents__icontains=q)
        elif search_type == "writer":
            boards = boards.filter(writer__username__icontains=q)
        elif search_type == "sentence":
            boards = boards.filter(sentence__sentence__icontains=q)
        paginator = Paginator(boards, 10)
        pagenum = request.GET.get('page')
        boards = paginator.get_page(pagenum)

        context = {
            'boards' : boards,
            'q' : q,
            'type' : search_type,

board/templates/board_public/board_public_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>일반인 상세 페이지 - 이그웹</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/static/css/videoDetail.css">
    <link rel="icon" sizes="192x192" href="/static/img/favicon.png">
    <nav class="navbar navbar-expand-sm fixed-top navbackground navmargin">    
        <div class="container-fluid"> 
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">        
                <span class="navbar-toggler-icon togglers" ></span>    
            </button>     
            <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">        
                <ul class="navbar-nav mt-2 menugroup">
                  {% if request.user.is_authenticated %}
                  <li class="nav-item mr-3">            
                      <a class="nav-link menu randommenu" href="{% url 'logout' %}" data-mid="0">로그아웃</a>        
                  </li>
                  {% else %}
                  <li class="nav-item mr-3">            
                      <a class="nav-link menu randommenu" href="{% url 'rwordpage' %}" data-mid="0">로그인</a>        
                  </li>
                  {% endif %}           
                    <li class="nav-item mr-3" data-mid="0">            
                        <a class="nav-link menu randommenu" href="{% url 'rwordpage' %}" data-mid="0">랜덤 단어 생성하기</a>        
                    </li>        
                    <li class="nav-item mr-3" data-mid="1">            
                        <a class="nav-link menu" href="{% url 'rwordboard' %}" data-mid="1">문장 공유하기</a>        
                    </li>        
                    <li class="nav-item mr-3" data-mid="2">            
                        <a class="nav-link menu" href="{% url 'board:board_public_list' %}" data-mid="2">일반인 게시판</a>        
                    </li>        
                    <li class="nav-item mr-3">            
                        <a class="nav-link menu" href="{% url 'board:board_science_list' %}" data-mid="3">과학자 게시판</a>        
                    </li>        
                </ul>    
            </div>    
        </div>
    </nav>
    <style>
      .notice:hover {
        color: #f9ffaa;
        text-decoration: underline;
            
      }
      .notice {
        color: #C0C53F;
        text-decoration: none;
      }
    </style>
</head>
<body>
    <section class="main-section">
        <div class="contents">
            <!--영상 (560:315 비율) width="1008" height="567"-->
            <!--<div class="main-video">  
                <iframe width="1008" height="567" src="https://www.youtube.com/embed/xTY0SlyVfCQ?autoplay=1&mute=1&controls=1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div> --> 
          <div class="info">
            <div class="row">
              <h3 class="video-title col-10">{{ board.title }}</h3>
              <!--좋아요 버튼-->
              <div class="like-button-div col-2">
                {% if request.user.is_authenticated %}
                <form class="d-inline like-button" action="{% url 'board:likes' board.pk %}" method='POST'>
                  {% csrf_token %}
                  {% if user in board.like_users.all %}
                    <button class="btn btn-link text-danger">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
                        <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                      </svg>
                    </button>
                  {% else %}
                    <button class="btn btn-link text-danger">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart" viewBox="0 0 16 16">
                        <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
                      </svg>
                    </button>
                  {% endif %}
                </form>
                {% endif %}
              </div>
            </div>
            <div class="video-below">
              <div class="row">
                <div class="date col">
                  <p class="d-inline">게시일</p>
                  <p class="d-inline date-num text-light">{{ board.write_dttm }}</p>
                </div>
                <div class="hits col">
                    <p class="d-inline">조회수</p>
                    <p class="d-inline hits-num text-light">{{ board.hits }}</p>
                </div>
                {% if messages %}
                <div>
                    {% for message in messages %}
                    <a href="/accounts/login">{{ message.message }}</a>
                    {% endfor %}
                </div>
                {% endif %}
                <div class="like col">
                    <p>좋아요</p>
                    <p class="text-light">{{ like_num }}</p>
                </div>
              </div>              
            </div>
            <hr>
            <div class="float-end">
              {% if user == board.writer %}
              <a class="smaller-gray user-func d-inline" href="/board/public/detail/{{ board.id }}/modify/">수정</a>
              <p class="d-inline">|</p>
              <a class="smaller-gray user-func d-inline" href="/board/public/detail/{{ board.id }}/delete/">삭제</a>
              {% endif %}
            </div>
            <p id="box-name">활용한 문장 : </p>
            <div id="sentence-box">
                <h3 class="sentence"><a href="#">{{ board.sentence }}</a></h3>
            </div>
            <div class="writer">
                <p>{{ board.writer }}</p>
                <p>님의 아이디어</p>
            </div>
            <hr id="idea-line d-blcok">
            <div class="main-info">
                <p class="video-size">
                {{ board.contents|safe }}  
                </p>
            </div>
            <hr class="first-line">
            <!--댓글창-->
            <div style="padding-bottom: 20px;">
              {% if comments %}
              <div class="d-block comment-div" style="float: left;">
                  <h5 class="comment-num"><strong>댓글&nbsp;</strong></h5>
                  <h5 class="comment-num"><strong>{{ comments|length }} 개</strong></h5>
              </div>
              {% endif %}
              <div class="d-blcok" style="float: left;">
              {% if not comments %}
                <h5 class="comment-num"><strong>댓글&nbsp;</strong></h5>
                <h5 class="comment-num"><strong>0 개</strong></h5>
              {% endif %}
              </div>
              <!-- 댓글생성 -->
              {% if request.user.is_authenticated %}
              <div class="d-block commentdDiv">
                <form class="text-add" action="{% url 'board:comments_create' board.pk %}" method="POST">
                  {% csrf_token %}
                  {{ comment_form.content }}
                  <input class="comment-input-button" type="submit" value="댓글 입력">
                </form>
              </div>                
              {% else %}
              <div class="d-block" style="float: left; margin: 10px; padding-top: 50px; padding-bottom: 20px; margin-left: -55px;">
                <a class="notice" style="text-align: left; font-family:'nanumsquare';" href="/">댓글을 작성하려면 로그인하세요.</a>
              </div>
              {% endif %}    
              <!--댓글 리스트-->
              {% for comment in comments %}
              <div class="row comments-div">
                <div class="comment col-10">
                  <b>{{ comment.user }}&nbsp;&nbsp;&nbsp;</b>{{ comment.content }}
                </div>
              <!--댓글 삭제 버튼-->
                {% if user == comment.user %}
                <form class="col-2 comment-delete" action="{% url 'board:comments_delete' board.pk comment.pk %}" method="POST" class="d-inline">
                  {% csrf_token %}
                  <input class="comment-delete-input" type="submit" value="삭제">
                </form>
                {% endif %}                                           
              </div>                                                                                                                                                                                                                                                                                            
              {% endfor %}        
                  
            </div>
          </div>
        </div>
        
    </section>
    <section id="footer"> <!--footer-->
        <div class="container-fluid">
            <footer class="align-items-center fbox">
              <img src="/static/img/footerImg.png" width="10%" class="footerImg">
              <p class="footertext">© 2022 Ig-Web for IgNobel Prize</p>
            </footer>
          </div>
    </section>
</body>
</html>